version: '3.8'
services:
  frontend:
    container_name: yt_dl_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    # depends_on:
    #   - nginx
    networks:
      - app-network

  backend:
    container_name: yt_dl_backend
    build: ./backend
    ports:
      - "8000:8000"
    # depends_on:
    #   - nginx
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: yt_dl_nginx
    ports:
      - "80:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
      # - frontend
      # - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge