version: '3.8'
services:
  frontend:
    container_name: yt_dl_frontend
    build: ./frontend
    networks:
      - app-network

  backend:
    container_name: yt_dl_backend
    build: ./backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: yt_dl_nginx
    ports:
      - "80:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge